apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
    spec:
      serviceAccountName: webhooksa
      containers:
      - name: webhook-container
        image: webhook1329.azurecr.io/webhook:latest
        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: webhook
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: webhook
